# Generated by Django 5.1.3 on 2024-12-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobshortlists", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobtype",
            old_name="type",
            new_name="job_type",
        ),
    ]
