# Generated by Django 5.1.3 on 2024-12-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobshortlists", "0002_rename_type_jobtype_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="job_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
