# Generated by Django 5.1.3 on 2024-12-10 16:29

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobshortlists", "0003_jobapplication_job_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="max_salary",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=4,
                default_currency="INR",
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="min_salary",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=4,
                default_currency="INR",
                max_digits=19,
                null=True,
            ),
        ),
    ]
